### ISSUE TITLE
Add scripts and/or notes for using GPG

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/security-team#3]
I certainly don't ever remember how to do anything and am constantly googling, would be cool to record note and scripts here which are hardcoded with our key.

**Comment by steveklabnik** [comment]
I personally point people to this page: http://futureboy.us/pgp.html

**Comment by even8811** [comment]
I would like to say hello and thank you for these lessons. 
$ chgrp-R www-data /srv/native
