### ISSUE TITLE
Configure a security policy for rust-lang/* repositories

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/security-team#5]
Visiting https://github.com/rust-lang/rust/security/policy shows that no policy is configured, but we do indeed have a [security policy](https://www.rust-lang.org/policies/security)! Let's do the necessary steps to configure GitHub's UI to show that we have a security policy.

@pietroalbini you mentioned that we could create a `.github` repository to configure this, would you mind looking into doing that?

**Comment by emilyalbini** [comment]
Created [rust-lang/.github](https://github.com/rust-lang/.github) and [forked it](https://github.com/rust-lang-nursery/.github) into the nursery. The advisory [looks like this](https://github.com/rust-lang/security-team/security/policy).
